version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    docker:
      - image: exilesprx/rustuino:devel
    steps:
      - checkout
      - run: cargo update
      - run: cargo build
      - store_artifacts:
          path: target
          destination: build
  release-build:
    docker:
      - image: exilesprx/rustuino:$CIRCLE_TAG
    steps:
      - checkout
      - run: cargo update
      - run: cargo build
      - store_artifacts:
          path: target
          destination: build

workflows:
  feature:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
                - develop
            tags:
              ignore: /v.*/
  devel:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: devel
          path: .docker
          filters:
            branches:
              only: develop
            tags:
              ignore: /v.*/
      - build:
          requires:
            - docker/publish
          filters:
            branches:
              only: develop
            tags:
              ignore: /v.*/
  release:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: $CIRCLE_TAG
          path: .docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - release-build:
          requires:
            - docker/publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/