version: 2.1

orbs:
  docker: circleci/docker@2.2.0

executors:
  rustuino:
    parameters:
      tag:
        default: "devel"
        type: string
    docker:
      - image: exilesprx/rustuino:<<parameters.tag>>

commands:
  update-and-build:
    steps:
      - checkout
      - run: cargo update
      - run: cargo build
      - store_artifacts:
          path: target
          destination: build

jobs:
  devel-build:
    executor:
      name: rustuino
      tag: "devel"
    steps:
      - update-and-build
  latest-build:
    executor:
      name: rustuino
      tag: "latest"
    steps:
      - update-and-build
  release-build:
    executor:
      name: rustuino
      tag: $CIRCLE_TAG
    steps:
      - update-and-build

workflows:
  feature:
    jobs:
      - devel-build:
          filters:
            branches:
              ignore:
                - main
                - develop
            tags:
              ignore: /v.*/
  devel:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: devel
          path: .docker
          use-buildkit: true
          filters:
            branches:
              only: develop
      - devel-build:
          requires:
            - docker/publish
          filters:
            branches:
              only: develop
  staging:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: latest
          path: .docker
          use-buildkit: true
          filters:
            branches:
              only: main
      - latest-build:
          requires:
            - docker/publish
          filters:
            branches:
              only: main
  release:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: $CIRCLE_TAG
          path: .docker
          use-buildkit: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - release-build:
          requires:
            - docker/publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/