version: 2.1

orbs:
  docker: circleci/docker@2.5.0

executors:
  rustuino:
    parameters:
      tag:
        default: "latest"
        type: string
    docker:
      - image: exilesprx/rustuino:<<parameters.tag>>

commands:
  update-and-build:
    steps:
      - checkout
      - run: cargo update
      - run: cargo build

jobs:
  latest-build:
    executor:
      name: rustuino
      tag: "latest"
    steps:
      - update-and-build
  release-build:
    executor:
      name: rustuino
      tag: $CIRCLE_TAG
    steps:
      - update-and-build

workflows:
  feature:
    jobs:
      - latest-build:
          filters:
            branches:
              ignore:
                - main
                - develop
            tags:
              ignore: /v.*/
  staging:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: latest
          path: .docker
          use-buildkit: true
          cache_from: exilesprx/rustuino:latest
          filters:
            branches:
              only: main
      - latest-build:
          requires:
            - docker/publish
          filters:
            branches:
              only: main
  release:
    jobs:
      - docker/publish:
          image: exilesprx/rustuino
          tag: $CIRCLE_TAG
          path: .docker
          use-buildkit: true
          cache_from: exilesprx/rustuino:latest
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - release-build:
          requires:
            - docker/publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/